<a href="https://colab.research.google.com/github/leandroclv/polars_udemy/blob/main/condicional_manipulacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import polars as pl

In [2]:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
df = pl.read_csv(url)
df.head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [11]:
df2 = (df.with_columns(
    pl.when(pl.col('tip') > 5)
      .then(pl.lit('alta'))
      .otherwise(pl.lit('normal'))
      .alias('categoria_gorjeta'))
    .sort('tip', descending=True)
)
df2.select(['total_bill', 'tip', 'categoria_gorjeta']).head()

shape: (5, 3)
┌────────────┬──────┬───────────────────┐
│ total_bill ┆ tip  ┆ categoria_gorjeta │
│ ---        ┆ ---  ┆ ---               │
│ f64        ┆ f64  ┆ str               │
╞════════════╪══════╪═══════════════════╡
│ 50.81      ┆ 10.0 ┆ alta              │
│ 48.33      ┆ 9.0  ┆ alta              │
│ 39.42      ┆ 7.58 ┆ alta              │
│ 48.27      ┆ 6.73 ┆ alta              │
│ 34.3       ┆ 6.7  ┆ alta              │
└────────────┴──────┴───────────────────┘