<a href="https://colab.research.google.com/github/leandroclv/polars_udemy/blob/main/introducao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import polars as pl

In [2]:
#Criando o dataframe
df = pl.DataFrame({
    'nome': ['Alice', 'Bob', 'Charlie', 'David'],
    'idade': [25, 30, 35, 40],
    'cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre']
})

In [3]:
df

shape: (4, 3)
┌─────────┬───────┬────────────────┐
│ nome    ┆ idade ┆ cidade         │
│ ---     ┆ ---   ┆ ---            │
│ str     ┆ i64   ┆ str            │
╞═════════╪═══════╪════════════════╡
│ Alice   ┆ 25    ┆ São Paulo      │
│ Bob     ┆ 30    ┆ Rio de Janeiro │
│ Charlie ┆ 35    ┆ Belo Horizonte │
│ David   ┆ 40    ┆ Porto Alegre   │
└─────────┴───────┴────────────────┘

In [5]:
#Exemplo de leitura csv público
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'
df = pl.read_csv(url)
df.head()

shape: (5, 7)
┌────────────┬──────┬────────┬────────┬─────┬────────┬──────┐
│ total_bill ┆ tip  ┆ sex    ┆ smoker ┆ day ┆ time   ┆ size │
│ ---        ┆ ---  ┆ ---    ┆ ---    ┆ --- ┆ ---    ┆ ---  │
│ f64        ┆ f64  ┆ str    ┆ str    ┆ str ┆ str    ┆ i64  │
╞════════════╪══════╪════════╪════════╪═════╪════════╪══════╡
│ 16.99      ┆ 1.01 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 10.34      ┆ 1.66 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 21.01      ┆ 3.5  ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 3    │
│ 23.68      ┆ 3.31 ┆ Male   ┆ No     ┆ Sun ┆ Dinner ┆ 2    │
│ 24.59      ┆ 3.61 ┆ Female ┆ No     ┆ Sun ┆ Dinner ┆ 4    │
└────────────┴──────┴────────┴────────┴─────┴────────┴──────┘

In [6]:
#Ver colunas
print(df.columns)

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

In [8]:
#Ver tipo de dados
print(df.dtypes)

[Float64, Float64, String, String, String, String, Int64]

In [9]:
#Contar numeros de linhas
print(df.shape)

(244, 7)

In [10]:
#Estatísticas descritivas
print(df.describe())

shape: (9, 8)
┌────────────┬────────────┬──────────┬────────┬────────┬──────┬────────┬──────────┐
│ statistic  ┆ total_bill ┆ tip      ┆ sex    ┆ smoker ┆ day  ┆ time   ┆ size     │
│ ---        ┆ ---        ┆ ---      ┆ ---    ┆ ---    ┆ ---  ┆ ---    ┆ ---      │
│ str        ┆ f64        ┆ f64      ┆ str    ┆ str    ┆ str  ┆ str    ┆ f64      │
╞════════════╪════════════╪══════════╪════════╪════════╪══════╪════════╪══════════╡
│ count      ┆ 244.0      ┆ 244.0    ┆ 244    ┆ 244    ┆ 244  ┆ 244    ┆ 244.0    │
│ null_count ┆ 0.0        ┆ 0.0      ┆ 0      ┆ 0      ┆ 0    ┆ 0      ┆ 0.0      │
│ mean       ┆ 19.785943  ┆ 2.998279 ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.569672 │
│ std        ┆ 8.902412   ┆ 1.383638 ┆ null   ┆ null   ┆ null ┆ null   ┆ 0.9511   │
│ min        ┆ 3.07       ┆ 1.0      ┆ Female ┆ No     ┆ Fri  ┆ Dinner ┆ 1.0      │
│ 25%        ┆ 13.37      ┆ 2.0      ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.0      │
│ 50%        ┆ 17.81      ┆ 2.92     ┆ null   ┆ null   ┆ null ┆ null   ┆ 2.0      │
│ 75%        ┆ 24.08      ┆ 3.55     ┆ null   ┆ null   ┆ null ┆ null   ┆ 3.0      │
│ max        ┆ 50.81      ┆ 10.0     ┆ Male   ┆ Yes    ┆ Thur ┆ Lunch  ┆ 6.0      │
└────────────┴────────────┴──────────┴────────┴────────┴──────┴────────┴──────────┘